### PR TITLE
Problem with typo in README.md.

### PR DESCRIPTION
**Pull request by Casida**
Just typo in README.md in the second instance of the word: landscape.yaml.

### CODE REVIEW

**Review by Diaphteiros — APPROVED** [review]

**Comment by Diaphteiros** [comment]
Thanks for fixing that typo. However, to be able to merge that pull request, we need you to sign the CLA, even for a simple typo.

**Comment by Casida** [comment]
Note, I've 'signed' the CLA several times now but for some reason after checking it still is registering as not signed..?

**Comment by rfranzke** [comment]
@Casida squash your commits and push again. The PR incorporates three commits where one is authored by "Edward Howe" (not a GitHub user and the reason for the CLAassistant to complain).

**Comment by msohn** [comment]
The committer email address of all commits you are pushing needs to be associated to your Github account, visit https://github.com/settings/emails to check which email addresses you have registered.

**Comment by Diaphteiros** [comment]
Somehow it still says that the CLA is not signed ... could you check again if you can sign it again?

**Comment by Diaphteiros** [comment]
This has become invalid with commit https://github.com/gardener/landscape-setup-template/commit/c8c95423a9972722982b03bfd757701c5217c2b8 due to a rewriting of the readme which removed the relevant paragraph.

**Pull request closed without merging**
